Feat: 후기 질문 목록 조회 API 구현
UMC-PROTOTYNE/PROTOTYNE_BE pull request #35
Opened 2024-08-12 13:49 UTC by gaeul3303

## 📌 관련 이슈

#17
## ✨ PR 내용

후기 질문 목록 조회 API 구현
## 📚 레퍼런스 혹은 궁금한 사항들

1. 궁금한 점: 
     path variable을 투자 id가 아닌 product id로 했는데 맞을까요? 
    후기 질문 목록 필드들이 product table에 있어서요..
3. 수정해야 할 점:
     product 테이블에 question6 필드(이미지 문항)를 추가해야 할 것 같습니다.
## 📸 스크린샷(선택)

![image](https://github.com/user-attachments/assets/e76bdbca-4753-471a-b9f8-025034e35b54)

2024-08-13 13:14 UTC, PROMLEE requested changes
수고하셨습니다 😄 
1. 음 이거 관련해서는 pm에게 물어보겠습니다.
2. 추가 구매 의사 문항과 이미지 문항(6, 7번)은 고정이라 따로 전달하지 않아도 됩니다!

코드 리뷰 확인해주세요!

2024-08-13 13:14 UTC, PROMLEE commented on src/main/java/com/prototyne/converter/ProductConverter.java
이미 develop 브랜치에 동일 파일 명, 동일 함수가 존재합니다! 😢 
ReviewConverter.java로 파일 명을 바꿔 주실 수 있나요?

2024-08-13 13:14 UTC, PROMLEE commented on src/main/java/com/prototyne/web/controller/ReviewController.java
> +        FeedbackImageDTO CreateFeedbacksImage = feedbackService.CreateFeedbacksImage(investmentId, feedbackImageDTO, accessToken);
현재 CreateFeedbacksImage 함수가 주석 처리 되어있네요 확인 부탁합니다!

2024-08-13 15:38 UTC, gaeul3303 commented on src/main/java/com/prototyne/web/controller/ReviewController.java
> +        FeedbackImageDTO CreateFeedbacksImage = feedbackService.CreateFeedbacksImage(investmentId, feedbackImageDTO, accessToken);
오류가 나서 주석처리했습니다! 오류 수정할게요

2024-08-13 19:24 UTC, gaeul3303 commented
![image](https://github.com/user-attachments/assets/0e7a952b-049b-4f16-8f5a-06ac2cebe144)
후기 작성 텍스트 API에서 request body를 answer1~6로만 수정해야 하는지 궁금합니다.

2024-08-14 05:36 UTC, PROMLEE commented
> ![image](https://private-user-images.githubusercontent.com/84903260/357545319-0e7a952b-049b-4f16-8f5a-06ac2cebe144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTQwMDAsIm5iZiI6MTcyMzYxMzcwMCwicGF0aCI6Ii84NDkwMzI2MC8zNTc1NDUzMTktMGU3YTk1MmItMDQ5Yi00ZjE2LThmNWEtMDZhYzJjZWJlMTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA1MzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjViOTgyMjk3ODQwYTRiNjdkYmUzZDRhOGUwNjhmNTAwYjM4MmE1ODg0ZjUyYmNiYzQ0NzJjNzAzOGVkZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.99k_-ne7PbHhcoxMHDCUaWkyOLEV7TinIq2SdXztpPw) 후기 작성 텍스트 API에서 request body를 answer1~6로만 수정해야 하는지 궁금합니다.

네 answer 1~6을 제외한 나머지는 필요 없는 항목이네요!

2024-08-14 18:58 UTC, gaeul3303 commented
![image](https://github.com/user-attachments/assets/9433cd01-b50c-4066-89a7-903110b8c5a2)
후기 작성 텍스트 API request body 수정했습니다.
![image](https://github.com/user-attachments/assets/c176611e-a540-4d31-81c0-147554f17c10)
후기 작성 이미지 API 테스트 결과
![image](https://github.com/user-attachments/assets/552e4e6d-d78b-416a-ba2e-8b7f6a9f6630)
후기 작성 이미지 API에서 feedback ID와 연결되는지 로그 출력 결과입니다.

2024-08-15 17:11 UTC, gaeul3303 commented
![image](https://github.com/user-attachments/assets/25ab349b-c3a6-4b7f-9eee-244840019069)
![image](https://github.com/user-attachments/assets/027c1392-1f83-4154-99e8-b940726bfc43)

티켓 사용 내역 조회 API로 티켓 정보 저장되는지 확인했습니다!

2024-08-18 01:54 UTC, PROMLEE requested changes
>궁금한 점
>
>체험 신청 API에서 노션에 있는 API 명세서를 보면 엔드 포인트가 /application/{id} 인데 메소드가 POST니까 id값이 없어야 하지 않는지 궁금합니다. (id값을 제외했는데 적어야 한다면 수정하겠습니다!)
>
>체험 신청 API에서 response값을 apply만 나오도록 했는데 더 추가해야 할 부분이 있을까요?
>
>티켓에 대한 정보를 저장했는지는 아직 확인 못했습니다. 테스트는 내일 다시 해볼게요!

수고하셨습니다 😄 

1. 메소드와 상관없이 id 값(식별값)은 path variable 로 받는 것이 좋습니다! 수정해주세요

2. 체험 신청 API에서 response값은 일단은 충분할 것 같습니다!

2024-08-18 01:54 UTC, PROMLEE commented on src/main/java/com/prototyne/service/FeedbackService/FeedbackServiceImpl.java
> +        Feedback feedback = feedbackRepository.findByInvestmentId(investmentId).orElseThrow(() -> new TempHandler(ErrorStatus.FEEDBACK_ERROR_ID));
investmentId를 기준으로 feedback 테이블에서 정보를 찾는 이유가 있을까요 ❓ 
리뷰 작성 시 feedback 테이블에 새로운 정보를 추가하는 것이라 feedback 테이블에 관련 정보가 없을 수 있습니다!
이미지 관련도 마찬가지입니다!

2024-08-18 01:54 UTC, PROMLEE commented on src/main/java/com/prototyne/service/FeedbackService/FeedbackServiceImpl.java
> +
이미지 개수 (1~3개)에 대한 에러 처리도 있으면 좋겠군요!

2024-08-18 01:54 UTC, PROMLEE commented on src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
> +    public InvestmentDTO.ApplicationResponse Application(String accessToken,Long productId, String ticketName, String ticketDesc) {
티켓 정보를 저장할 때 티켓 이름과 티켓 설명을 쿼리로 받지 않고 우리 테이블에 저장되어있는 정보를 바탕으로 자동 작성되게 할 수는 없을까요?

2024-08-18 22:22 UTC, gaeul3303 commented on src/main/java/com/prototyne/service/FeedbackService/FeedbackServiceImpl.java
> +        Feedback feedback = feedbackRepository.findByInvestmentId(investmentId).orElseThrow(() -> new TempHandler(ErrorStatus.FEEDBACK_ERROR_ID));
investmentId를 기준으로 Feedback테이블에 해당 데이터가 있으면 수정하고 없으면 객체를 생성하여 필드 값을 추가하도록 수정하였습니다!

2024-08-18 22:22 UTC, gaeul3303 commented on src/main/java/com/prototyne/service/FeedbackService/FeedbackServiceImpl.java
> +
수정하였습니다!

2024-08-18 22:22 UTC, gaeul3303 commented on src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
> +    public InvestmentDTO.ApplicationResponse Application(String accessToken,Long productId, String ticketName, String ticketDesc) {
수정하였습니다!

2024-08-19 07:32 UTC, PROMLEE requested changes
수고하셨습니다 👍 
리뷰 확인해주세요!

2024-08-19 07:32 UTC, PROMLEE commented on src/main/java/com/prototyne/web/controller/ApplicationController.java
> +    public ApiResponse<InvestmentDTO.ApplicationResponse> Application(HttpServletRequest token, @PathVariable("eventId") Long eventId, Long productId){
productId를 직접 받기보다는 eventId만 받고 해당 데이터에서 외래키로 저장되어있는 product를 뽑아내는 것이 더 좋아보입니다!

2024-08-19 07:51 UTC, PROMLEE approved these changes
LGTM 👍 
수고하셨습니다 😄

2024-08-19 07:51 UTC, merged